#!/usr/bin/env bash
#
# install-anserini.sh — Download the Anserini fatjar and verify it works.
#
# Usage:
#   bash scripts/install-anserini.sh
#
# Sets ANSERINI_JAR in the current shell and writes it to a .env file.
#
set -euo pipefail

# ---- Config ----
REQUIRED_JAVA_MAJOR=21

# ---- 1. Check Java ----
echo "==> Checking Java..."
if ! command -v java &>/dev/null; then
  echo "ERROR: java not found on PATH. Install JDK $REQUIRED_JAVA_MAJOR."
  exit 1
fi

JAVA_VER=$(java -version 2>&1 | head -1)
echo "    $JAVA_VER"

JAVA_MAJOR=$(java -version 2>&1 | grep -oP 'version "?\K\d+' | head -1 || true)
if [ -z "$JAVA_MAJOR" ]; then
  JAVA_MAJOR=$(java -version 2>&1 | grep -oP '"([^"]+)"' | tr -d '"' | cut -d. -f1)
fi

if [ "$JAVA_MAJOR" != "$REQUIRED_JAVA_MAJOR" ]; then
  echo "ERROR: Java $REQUIRED_JAVA_MAJOR required, found Java $JAVA_MAJOR."
  exit 1
fi
echo "    Java $JAVA_MAJOR OK."

# ---- 2. Discover latest Anserini release ----
echo "==> Checking latest Anserini release..."
ANSERINI_VERSION="${ANSERINI_VERSION:-}"
if [ -z "$ANSERINI_VERSION" ]; then
  ANSERINI_VERSION=$(curl -sS https://repo1.maven.org/maven2/io/anserini/anserini/maven-metadata.xml \
    | sed -n 's:.*<release>\(.*\)</release>.*:\1:p')
fi

if [ -z "$ANSERINI_VERSION" ]; then
  echo "ERROR: Could not determine Anserini version."
  exit 1
fi
echo "    Anserini version: $ANSERINI_VERSION"

# ---- 3. Download fatjar ----
ANSERINI_JAR="anserini-${ANSERINI_VERSION}-fatjar.jar"

if [ -f "$ANSERINI_JAR" ]; then
  echo "==> Fatjar already exists: $ANSERINI_JAR"
else
  echo "==> Downloading $ANSERINI_JAR..."
  if command -v curl &>/dev/null; then
    curl -fL -o "$ANSERINI_JAR" \
      "https://repo1.maven.org/maven2/io/anserini/anserini/${ANSERINI_VERSION}/${ANSERINI_JAR}"
  else
    wget "https://repo1.maven.org/maven2/io/anserini/anserini/${ANSERINI_VERSION}/${ANSERINI_JAR}"
  fi
fi

test -f "$ANSERINI_JAR" || { echo "ERROR: Fatjar not found: $ANSERINI_JAR"; exit 1; }
echo "    Fatjar: $ANSERINI_JAR ($(du -h "$ANSERINI_JAR" | cut -f1))"

# ---- 4. Smoke test ---- #
echo "==> Running CACM smoke test..."
java -cp "$ANSERINI_JAR" io.anserini.search.SearchCollection \
  -threads 1 \
  -index cacm \
  -topics cacm \
  -output run.cacm.bm25.txt \
  -hits 1000 \
  -bm25

if [ ! -f run.cacm.bm25.txt ]; then
  echo "ERROR: Smoke test did not produce run.cacm.bm25.txt."
  exit 1
fi
echo "    Smoke test run generated: run.cacm.bm25.txt"

# ---- 5. Verify scores ----
echo "==> Verifying CACM scores..."
java -cp "$ANSERINI_JAR" io.anserini.eval.TrecEval \
  -c \
  -m map \
  -m P.30 \
  cacm \
  run.cacm.bm25.txt | tee eval.cacm.bm25.txt

if ! grep -Eq 'map[[:space:]]+all[[:space:]]+0\.3123' eval.cacm.bm25.txt; then
  echo "ERROR: MAP score mismatch!"
  grep map eval.cacm.bm25.txt
  exit 1
fi

if ! grep -Eq 'P_30[[:space:]]+all[[:space:]]+0\.1942' eval.cacm.bm25.txt; then
  echo "ERROR: P30 score mismatch!"
  grep P_30 eval.cacm.bm25.txt
  exit 1
fi

echo "    Scores verified: MAP=0.3123, P30=0.1942"

# ---- 6. Write env file ----
cat > .env <<EOF
# Generated by scripts/install-anserini.sh
ANSERINI_JAR=$ANSERINI_JAR
ANSERINI_VERSION=$ANSERINI_VERSION
EOF

echo ""
echo "============================================"
echo " Anserini fatjar installed and verified!"
echo "============================================"
echo ""
echo "   ANSERINI_JAR=$ANSERINI_JAR"
echo ""
echo " To start the REST server:"
echo "   source .env"
echo "   bash scripts/start-backend.sh"
echo ""
echo " To start the frontend (in another terminal):"
echo "   bash scripts/start-frontend.sh"
echo ""
